import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author brain
 * @version 1.0
 * @since 4/2/2017
 */
public class AdminGUITEMP extends JFrame {
	private JList TicketDisplay;
	private JPanel MainPanel;
	private JButton addFlightButton;
	private JButton addFlightFromFileButton;
	private JButton cancelTicketButton;
	private JPanel SouthPanel;
	private JPanel NorthPanel;

	public AdminGUITEMP() {
		addFlightButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {

			}
		});
		addFlightFromFileButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {

			}
		});
		cancelTicketButton.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?");
			}
		});
	}

	public static void main(String[] args) {
		try {
			UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
		} catch (Exception e) {
			e.printStackTrace();
		}
		AdminGUITEMP test = new AdminGUITEMP();
		test.$$$setupUI$$$();
		test.setSize(200, 200);
		test.setVisible(true);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		MainPanel = new JPanel();
		MainPanel.setLayout(new BorderLayout(0, 0));
		TicketDisplay = new JList();
		TicketDisplay.setSelectionMode(0);
		MainPanel.add(TicketDisplay, BorderLayout.CENTER);
		SouthPanel = new JPanel();
		SouthPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		MainPanel.add(SouthPanel, BorderLayout.SOUTH);
		addFlightButton = new JButton();
		addFlightButton.setText("Add Flight");
		SouthPanel.add(addFlightButton);
		addFlightFromFileButton = new JButton();
		addFlightFromFileButton.setText("Add Flight from File");
		SouthPanel.add(addFlightFromFileButton);
		cancelTicketButton = new JButton();
		cancelTicketButton.setText("Cancel Ticket");
		SouthPanel.add(cancelTicketButton);
		NorthPanel = new JPanel();
		NorthPanel.setLayout(new BorderLayout(0, 0));
		MainPanel.add(NorthPanel, BorderLayout.NORTH);
		final JLabel label1 = new JLabel();
		label1.setText("Admin Management System");
		NorthPanel.add(label1, BorderLayout.NORTH);
		final JLabel label2 = new JLabel();
		label2.setText("Tickets");
		NorthPanel.add(label2, BorderLayout.CENTER);
		final JSeparator separator1 = new JSeparator();
		NorthPanel.add(separator1, BorderLayout.SOUTH);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return MainPanel;
	}
}
