import javax.swing.*;
import java.awt.*;

/**
 * @author brain
 * @version 1.0
 * @since 4/2/2017
 */
public class AdminGUI extends JFrame
{
	private JList list1;
	private JPanel panel1;
	private JButton button1;
	private JButton button2;
	private JButton button3;

	public static void main(String[] args)
	{
		try {
			UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
		} catch (Exception e) {
			e.printStackTrace();
		}
		AdminGUI test = new AdminGUI();
		test.$$$setupUI$$$();
		test.setSize(200, 200);
		test.setVisible(true);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panel1 = new JPanel();
		panel1.setLayout(new BorderLayout(0, 0));
		list1 = new JList();
		panel1.add(list1, BorderLayout.CENTER);
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		panel1.add(panel2, BorderLayout.SOUTH);
		button1 = new JButton();
		button1.setText("Button");
		panel2.add(button1);
		button2 = new JButton();
		button2.setText("Button");
		panel2.add(button2);
		button3 = new JButton();
		button3.setText("Button");
		panel2.add(button3);
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new BorderLayout(0, 0));
		panel1.add(panel3, BorderLayout.NORTH);
		final JLabel label1 = new JLabel();
		label1.setText("Admin Management System");
		panel3.add(label1, BorderLayout.NORTH);
		final JLabel label2 = new JLabel();
		label2.setText("Tickets");
		panel3.add(label2, BorderLayout.CENTER);
		final JSeparator separator1 = new JSeparator();
		panel3.add(separator1, BorderLayout.SOUTH);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panel1;
	}
}
