import javax.swing.*;
import java.awt.*;

/**
 * @author brain
 * @version 1.0
 * @since 4/2/2017
 */
public class PassengerGUITEMP {
	private JButton searchButton;
	private JButton clearSearchButton;
	private JTextField textField1;
	private JTextField textField2;
	private JTextField textField3;
	private JTextField textField4;
	private JTextField textField5;
	private JTextField textField6;
	private JTextField textField7;
	private JRadioButton clientIDRadioButton;
	private JRadioButton lastNameRadioButton;
	private JRadioButton clientTypeRadioButton;
	private JList<String> list;
	private JComboBox comboBox1;
	private JButton saveButton;
	private JButton deleteButton;
	private JButton clearButton;
	private JPanel MainPanel;
	private JPanel LeftTop;
	private JPanel Right;
	private JPanel Title;
	private JPanel LeftBot;
	private JLabel SearchResults;
	private JPanel LT1;
	private JPanel LT2;
	private JPanel LT3;
	private JPanel LT4;
	private JPanel LT5;
	private JPanel R1;
	private JPanel R2;
	private JPanel R3;
	private JPanel R4;
	private JPanel R5;
	private JPanel R6;
	private JPanel R7;
	private JPanel R8;
	private JPanel R9;
	private JScrollPane ScrollPane;
	private JLabel TitleLabel;
	private Container c;
	private PassengerGUI.Listener listener;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
	}
}
